openapi: 3.0.3
info:
  title: STD24205
  version: 1.0.0
  description: This is a specification of STD24205
servers:
  - url: 'http://localhost:8000'
tags:
  - name: Ping
    description: return pong
  - name: cars
    description: Operations related to cars
paths:
  /ping:
    get:
      tags:
        - Ping
      description: return a text pong
      schema:
        type: String
        example: pong
    /cars:
    post:
      tags:
        - cars
      responses:
        '202':
          content:
            application/json:
              schema:
                type: array
                items:
              schema:
                type: String
                name: identifier
              schema:
                type: String
                name: brand
              schema:
                type: String
                name: model
    get:
      description:
        type:
          application/JSON:
            schema:
              type: String
              name: identifier
            schema:
              type: String
              name: brand
            schema:
              type: String
              name: model
